### PR TITLE
fix: Index limit

### PR DESCRIPTION
**Pull request by crashzk**
https://cdn.discordapp.com/attachments/555816927680004116/1033394477332693032/unknown.png

### CODE REVIEW

**Comment by crashzk** [comment]
I changed the version just for one control.

@z1ntex

**Comment by NaathySz** [comment]
image
Cant fix it. Valve give a lot of headaches, fuck.

**Comment by z1ntex** [comment]
Try a new database connection

**Comment by NaathySz** [comment]
image
image

Stickers dont show in menu. The errors are in `menu.inc`. 
eItems already updated. Before yesterday, all was good.

**Comment by crashzk** [comment]
@NaathySz  Just download the version he just uploaded: https://github.com/z1ntex/CSGO_WeaponStickers

Update your eItems if you haven't already, and then restart your server, GG.

Plugin is all right, I updated here and everything ok.

**Comment by NaathySz** [comment]
@crashzk 
The problem is.. i did it, but not work ^^'

**Comment by NaathySz** [comment]
Nothing shows at stickers menu.

**Comment by NaathySz** [comment]
now got this when i try reload `eitems`

```
L 10/22/2022 - 20:39:32: [SM] Exception reported: Array index out-of-bounds (index 6006, limit 6000)

L 10/22/2022 - 20:39:32: [SM] Blaming: csgo_weaponstickers.smx
L 10/22/2022 - 20:39:32: [SM] Call stack trace:
L 10/22/2022 - 20:39:32: [SM]   [1] Line 162, C:\Users\artem\OneDrive\Ðàáî÷èé ñòîë\scripting\csgo_weaponstickers.sp::Frame_ItemsSync
```
YES, i updated BOTH

**Comment by crashzk** [comment]
Test @NaathySz: [CSGO Weapon Stickers IEM Rio Major 2022.zip](https://github.com/z1ntex/CSGO_WeaponStickers/files/9845470/CSGO.Weapon.Stickers.IEM.Rio.Major.2022.zip)

And remember, if updated SourceMod change:
```
Edit csgo/addons/sourcemod/configs/core.cfg => and set "FollowCSGOServerGuidelines" to "no";
```

**Comment by crashzk** [comment]
@z1ntex your new version has not been compiled. :)

**Comment by NaathySz** [comment]
xD fixed by compiling both.
thx crash.

**Pull request closed without merging**
